
server:
  port: 8877

spring:
  datasource:
    url: jdbc:mysql://www.shengouqiang.cn:3306/shen?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dandan19960813
  redis:
    host: www.shengouqiang.cn
    port: 6379
    database: 0
    password: shengouqiang
    timeout: 2s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: 1
        # 最大活跃连接数，负数为不限制
        max-active: -1

#以下可忽略
mybatis:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    com.scitc.cache.mapper : debug


debug:  true

cachename-ttl-config:
  config: false
  ttl-config-map:
    cacheName: 500